project:
  type: website

website:
  title: "Car Efficiency 1970-2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: plot-2.qmd
      - href: about.qmd
        text: About
      - href: Sources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



